### ISSUE TITLE
{onSelectJS}

### ISSUE THREAD

**Issue by alexmnyc** [brianhsu/lift-combobox#1]
The module is not working: on the client produced javascript is the following:

$("#F1083788637635YQXUZK").on("change", function(e) { 
        ${onSelectJS}
      });

where    ${onSelectJS} is undefined.

(scala 2.10, Lift 2.5-RC5)

**Comment by brianhsu** [comment]
It should be fixed now. 

Pelease try to update to `"net.liftmodules" %% "combobox" % "2.5-RC2-0.4"` to see if it could work. ;-)

**Comment by alexmnyc** [comment]
Thanks, Brian!

There was also one more I had to fix:

381        -          return {"id": ${NewItemPrefix} + term, "text": term};  
    381    +          return {"id": '${NewItemPrefix}' + term, "text": term};

**Comment by brianhsu** [comment]
Thanks for your notice, I'm not really familiar with JavaScript. :p
